Repository dotnet/xharness, pull requests merged in 2024-10, with the labels that each got.

#1291 [android] Add warning message when Android devices have package verification enabled
  src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
  src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
Labels: android

#1301 Add docs with high-level architecture overview
  docs/README.md
  docs/xharness-overview.svg
Labels: documentation

#1302 Improve exception handling
  src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
  src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs
  src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs
  src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/Arguments/DeviceArchitectureArgument.cs
  src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Arguments/TargetArgument.cs
  src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
  src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
  src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
  src/Microsoft.DotNet.XHarness.Common/Execution/MacOSProcessManager.cs
  src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs
  src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs
  src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
  src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs
Labels: enhancement

#1304 List platforms and commands in docs
  docs/high-level-architecture.md
Labels: documentation

#1305 [release/9.0] Improve exception handling
  src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
  src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs
  src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs
  src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/Arguments/DeviceArchitectureArgument.cs
  src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Arguments/TargetArgument.cs
  src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
  src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
  src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
  src/Microsoft.DotNet.XHarness.Common/Execution/MacOSProcessManager.cs
  src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs
  src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs
  src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
  src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs
Labels: enhancement

#1307 [sdl] Include cgmanifest.json generation for Android platform tools to be included in SBOM generation
  src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Labels: compliance

#1308 [sdl] Enable TSA and Policheck in the official build
  azure-pipelines.yml
Labels: compliance

#1309 [sdl] Add documentation on integrity checks for 3rd party dependencies
  docs/integrity-check.md
Labels: compliance
